# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Dispatch function for BigColSums
#' @param pBigMat SEXP container for the external pointer to the BigMatrix
#'   object
#' @useDynLib BigMatrixRcppTest
#' @import bigmemory
#' @import BH
#' @importFrom Rcpp evalCpp
#' @export
BigColSums <- function(pBigMat) {
    .Call('BigMatrixRcppTest_BigColSums', PACKAGE = 'BigMatrixRcppTest', pBigMat)
}

